// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: protos/flashSale_proto/flashSale.proto

package flashSale_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlashSaleProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId     string  `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OriginalPrice float32 `protobuf:"fixed32,4,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	DiscountPrice float32 `protobuf:"fixed32,5,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	Stock         int32   `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	IsActive      bool    `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *FlashSaleProduct) Reset() {
	*x = FlashSaleProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashSaleProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashSaleProduct) ProtoMessage() {}

func (x *FlashSaleProduct) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashSaleProduct.ProtoReflect.Descriptor instead.
func (*FlashSaleProduct) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{0}
}

func (x *FlashSaleProduct) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *FlashSaleProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlashSaleProduct) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FlashSaleProduct) GetOriginalPrice() float32 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *FlashSaleProduct) GetDiscountPrice() float32 {
	if x != nil {
		return x.DiscountPrice
	}
	return 0
}

func (x *FlashSaleProduct) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *FlashSaleProduct) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ProductId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId     string  `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	DescountPrice float32 `protobuf:"fixed32,2,opt,name=descount_price,json=descountPrice,proto3" json:"descount_price,omitempty"`
}

func (x *ProductId) Reset() {
	*x = ProductId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductId) ProtoMessage() {}

func (x *ProductId) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductId.ProtoReflect.Descriptor instead.
func (*ProductId) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{1}
}

func (x *ProductId) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductId) GetDescountPrice() float32 {
	if x != nil {
		return x.DescountPrice
	}
	return 0
}

type FlashSaleEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string              `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartTime   string              `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime     string              `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Products    []*FlashSaleProduct `protobuf:"bytes,6,rep,name=products,proto3" json:"products,omitempty"`
	IsActive    bool                `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *FlashSaleEvent) Reset() {
	*x = FlashSaleEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashSaleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashSaleEvent) ProtoMessage() {}

func (x *FlashSaleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashSaleEvent.ProtoReflect.Descriptor instead.
func (*FlashSaleEvent) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{2}
}

func (x *FlashSaleEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlashSaleEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlashSaleEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FlashSaleEvent) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *FlashSaleEvent) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *FlashSaleEvent) GetProducts() []*FlashSaleProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *FlashSaleEvent) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateFlashSaleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StartTime   string       `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime     string       `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Products    []*ProductId `protobuf:"bytes,5,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *CreateFlashSaleRequest) Reset() {
	*x = CreateFlashSaleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlashSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlashSaleRequest) ProtoMessage() {}

func (x *CreateFlashSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlashSaleRequest.ProtoReflect.Descriptor instead.
func (*CreateFlashSaleRequest) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFlashSaleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFlashSaleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFlashSaleRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateFlashSaleRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateFlashSaleRequest) GetProducts() []*ProductId {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateFlashSaleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *FlashSaleEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *CreateFlashSaleResponse) Reset() {
	*x = CreateFlashSaleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlashSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlashSaleResponse) ProtoMessage() {}

func (x *CreateFlashSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlashSaleResponse.ProtoReflect.Descriptor instead.
func (*CreateFlashSaleResponse) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFlashSaleResponse) GetEvent() *FlashSaleEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateFlashSaleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string              `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartTime   string              `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime     string              `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Products    []*FlashSaleProduct `protobuf:"bytes,6,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *UpdateFlashSaleRequest) Reset() {
	*x = UpdateFlashSaleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFlashSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlashSaleRequest) ProtoMessage() {}

func (x *UpdateFlashSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlashSaleRequest.ProtoReflect.Descriptor instead.
func (*UpdateFlashSaleRequest) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFlashSaleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFlashSaleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFlashSaleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateFlashSaleRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpdateFlashSaleRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UpdateFlashSaleRequest) GetProducts() []*FlashSaleProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

type UpdateFlashSaleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *FlashSaleEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *UpdateFlashSaleResponse) Reset() {
	*x = UpdateFlashSaleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFlashSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlashSaleResponse) ProtoMessage() {}

func (x *UpdateFlashSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlashSaleResponse.ProtoReflect.Descriptor instead.
func (*UpdateFlashSaleResponse) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateFlashSaleResponse) GetEvent() *FlashSaleEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type DeleteFlashSaleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteFlashSaleRequest) Reset() {
	*x = DeleteFlashSaleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFlashSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlashSaleRequest) ProtoMessage() {}

func (x *DeleteFlashSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlashSaleRequest.ProtoReflect.Descriptor instead.
func (*DeleteFlashSaleRequest) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFlashSaleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteFlashSaleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteFlashSaleResponse) Reset() {
	*x = DeleteFlashSaleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFlashSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlashSaleResponse) ProtoMessage() {}

func (x *DeleteFlashSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlashSaleResponse.ProtoReflect.Descriptor instead.
func (*DeleteFlashSaleResponse) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFlashSaleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListFlashSalesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFlashSalesRequest) Reset() {
	*x = ListFlashSalesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFlashSalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlashSalesRequest) ProtoMessage() {}

func (x *ListFlashSalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlashSalesRequest.ProtoReflect.Descriptor instead.
func (*ListFlashSalesRequest) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{9}
}

type ListFlashSalesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*FlashSaleEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *ListFlashSalesResponse) Reset() {
	*x = ListFlashSalesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFlashSalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlashSalesResponse) ProtoMessage() {}

func (x *ListFlashSalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlashSalesResponse.ProtoReflect.Descriptor instead.
func (*ListFlashSalesResponse) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{10}
}

func (x *ListFlashSalesResponse) GetEvents() []*FlashSaleEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type PurchaseProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity  int32  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UserId    string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *PurchaseProductRequest) Reset() {
	*x = PurchaseProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchaseProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseProductRequest) ProtoMessage() {}

func (x *PurchaseProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseProductRequest.ProtoReflect.Descriptor instead.
func (*PurchaseProductRequest) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{11}
}

func (x *PurchaseProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PurchaseProductRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PurchaseProductRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PurchaseProductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string            `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Product *FlashSaleProduct `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
}

func (x *PurchaseProductResponse) Reset() {
	*x = PurchaseProductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchaseProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseProductResponse) ProtoMessage() {}

func (x *PurchaseProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseProductResponse.ProtoReflect.Descriptor instead.
func (*PurchaseProductResponse) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{12}
}

func (x *PurchaseProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PurchaseProductResponse) GetProduct() *FlashSaleProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetActiveFlashSalesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetActiveFlashSalesRequest) Reset() {
	*x = GetActiveFlashSalesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActiveFlashSalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveFlashSalesRequest) ProtoMessage() {}

func (x *GetActiveFlashSalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveFlashSalesRequest.ProtoReflect.Descriptor instead.
func (*GetActiveFlashSalesRequest) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{13}
}

type GetActiveFlashSalesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActiveEvents []*FlashSaleEvent `protobuf:"bytes,1,rep,name=active_events,json=activeEvents,proto3" json:"active_events,omitempty"`
}

func (x *GetActiveFlashSalesResponse) Reset() {
	*x = GetActiveFlashSalesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActiveFlashSalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveFlashSalesResponse) ProtoMessage() {}

func (x *GetActiveFlashSalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_flashSale_proto_flashSale_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveFlashSalesResponse.ProtoReflect.Descriptor instead.
func (*GetActiveFlashSalesResponse) Descriptor() ([]byte, []int) {
	return file_protos_flashSale_proto_flashSale_proto_rawDescGZIP(), []int{14}
}

func (x *GetActiveFlashSalesResponse) GetActiveEvents() []*FlashSaleEvent {
	if x != nil {
		return x.ActiveEvents
	}
	return nil
}

var File_protos_flashSale_proto_flashSale_proto protoreflect.FileDescriptor

var file_protos_flashSale_proto_flashSale_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61,
	0x6c, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe8, 0x01, 0x0a, 0x10, 0x46, 0x6c, 0x61,
	0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x22, 0x51, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x25, 0x0a, 0x0e, 0x64, 0x65, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x64, 0x65, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0xdc, 0x01, 0x0a, 0x0e, 0x46, 0x6c, 0x61, 0x73, 0x68,
	0x53, 0x61, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x46, 0x6c,
	0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0xb0, 0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x22, 0x40, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0xc7, 0x01, 0x0a, 0x16, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53,
	0x61, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x73, 0x22, 0x40, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c,
	0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x25, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x33, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53,
	0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x61,
	0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x41,
	0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68,
	0x53, 0x61, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x6c, 0x0a, 0x16, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x60, 0x0a, 0x17, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c,
	0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x46, 0x6c,
	0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x53, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x46, 0x6c, 0x61, 0x73,
	0x68, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x32, 0xbf, 0x03, 0x0a, 0x10, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61,
	0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x12, 0x17, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c,
	0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x44, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61,
	0x6c, 0x65, 0x12, 0x17, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68,
	0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46,
	0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x12, 0x17, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53,
	0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x4c,
	0x69, 0x73, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x12, 0x16, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6c, 0x61, 0x73,
	0x68, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x46, 0x6c, 0x61, 0x73, 0x68,
	0x53, 0x61, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x46, 0x6c,
	0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x44, 0x0a, 0x0f, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x12, 0x17, 0x2e, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x50,
	0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x53, 0x61, 0x6c, 0x65, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_flashSale_proto_flashSale_proto_rawDescOnce sync.Once
	file_protos_flashSale_proto_flashSale_proto_rawDescData = file_protos_flashSale_proto_flashSale_proto_rawDesc
)

func file_protos_flashSale_proto_flashSale_proto_rawDescGZIP() []byte {
	file_protos_flashSale_proto_flashSale_proto_rawDescOnce.Do(func() {
		file_protos_flashSale_proto_flashSale_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_flashSale_proto_flashSale_proto_rawDescData)
	})
	return file_protos_flashSale_proto_flashSale_proto_rawDescData
}

var file_protos_flashSale_proto_flashSale_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_protos_flashSale_proto_flashSale_proto_goTypes = []any{
	(*FlashSaleProduct)(nil),            // 0: FlashSaleProduct
	(*ProductId)(nil),                   // 1: ProductId
	(*FlashSaleEvent)(nil),              // 2: FlashSaleEvent
	(*CreateFlashSaleRequest)(nil),      // 3: CreateFlashSaleRequest
	(*CreateFlashSaleResponse)(nil),     // 4: CreateFlashSaleResponse
	(*UpdateFlashSaleRequest)(nil),      // 5: UpdateFlashSaleRequest
	(*UpdateFlashSaleResponse)(nil),     // 6: UpdateFlashSaleResponse
	(*DeleteFlashSaleRequest)(nil),      // 7: DeleteFlashSaleRequest
	(*DeleteFlashSaleResponse)(nil),     // 8: DeleteFlashSaleResponse
	(*ListFlashSalesRequest)(nil),       // 9: ListFlashSalesRequest
	(*ListFlashSalesResponse)(nil),      // 10: ListFlashSalesResponse
	(*PurchaseProductRequest)(nil),      // 11: PurchaseProductRequest
	(*PurchaseProductResponse)(nil),     // 12: PurchaseProductResponse
	(*GetActiveFlashSalesRequest)(nil),  // 13: GetActiveFlashSalesRequest
	(*GetActiveFlashSalesResponse)(nil), // 14: GetActiveFlashSalesResponse
}
var file_protos_flashSale_proto_flashSale_proto_depIdxs = []int32{
	0,  // 0: FlashSaleEvent.products:type_name -> FlashSaleProduct
	1,  // 1: CreateFlashSaleRequest.products:type_name -> ProductId
	2,  // 2: CreateFlashSaleResponse.event:type_name -> FlashSaleEvent
	0,  // 3: UpdateFlashSaleRequest.products:type_name -> FlashSaleProduct
	2,  // 4: UpdateFlashSaleResponse.event:type_name -> FlashSaleEvent
	2,  // 5: ListFlashSalesResponse.events:type_name -> FlashSaleEvent
	0,  // 6: PurchaseProductResponse.product:type_name -> FlashSaleProduct
	2,  // 7: GetActiveFlashSalesResponse.active_events:type_name -> FlashSaleEvent
	3,  // 8: FlashSaleService.CreateFlashSale:input_type -> CreateFlashSaleRequest
	5,  // 9: FlashSaleService.UpdateFlashSale:input_type -> UpdateFlashSaleRequest
	7,  // 10: FlashSaleService.DeleteFlashSale:input_type -> DeleteFlashSaleRequest
	9,  // 11: FlashSaleService.ListFlashSales:input_type -> ListFlashSalesRequest
	13, // 12: FlashSaleService.GetActiveFlashSales:input_type -> GetActiveFlashSalesRequest
	11, // 13: FlashSaleService.PurchaseProduct:input_type -> PurchaseProductRequest
	4,  // 14: FlashSaleService.CreateFlashSale:output_type -> CreateFlashSaleResponse
	6,  // 15: FlashSaleService.UpdateFlashSale:output_type -> UpdateFlashSaleResponse
	8,  // 16: FlashSaleService.DeleteFlashSale:output_type -> DeleteFlashSaleResponse
	10, // 17: FlashSaleService.ListFlashSales:output_type -> ListFlashSalesResponse
	14, // 18: FlashSaleService.GetActiveFlashSales:output_type -> GetActiveFlashSalesResponse
	12, // 19: FlashSaleService.PurchaseProduct:output_type -> PurchaseProductResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_protos_flashSale_proto_flashSale_proto_init() }
func file_protos_flashSale_proto_flashSale_proto_init() {
	if File_protos_flashSale_proto_flashSale_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_flashSale_proto_flashSale_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FlashSaleProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ProductId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FlashSaleEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFlashSaleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFlashSaleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateFlashSaleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateFlashSaleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteFlashSaleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteFlashSaleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListFlashSalesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListFlashSalesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*PurchaseProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*PurchaseProductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GetActiveFlashSalesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_flashSale_proto_flashSale_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*GetActiveFlashSalesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_flashSale_proto_flashSale_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_flashSale_proto_flashSale_proto_goTypes,
		DependencyIndexes: file_protos_flashSale_proto_flashSale_proto_depIdxs,
		MessageInfos:      file_protos_flashSale_proto_flashSale_proto_msgTypes,
	}.Build()
	File_protos_flashSale_proto_flashSale_proto = out.File
	file_protos_flashSale_proto_flashSale_proto_rawDesc = nil
	file_protos_flashSale_proto_flashSale_proto_goTypes = nil
	file_protos_flashSale_proto_flashSale_proto_depIdxs = nil
}
